version: '2'
services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/yonobot
    depends_on:
      - mongo
  mongo:
    image: "mongo:3.6-stretch"
    ports:
      - "27020:27017"
